#!/bin/sh

manifest_add_previous_native_paths() {
	if ! manifest_has_owned_path "$MANIFEST_PREVIOUS_DIR"; then
		manifest_append_owned_path "$MANIFEST_PREVIOUS_DIR" || return 1
		MANIFEST_OWNED_COUNT=$((MANIFEST_OWNED_COUNT + 1))
	fi
	if ! manifest_has_owned_path "$MANIFEST_PREVIOUS_BINARY_PATH_FIXED"; then
		manifest_append_owned_path "$MANIFEST_PREVIOUS_BINARY_PATH_FIXED" || return 1
		MANIFEST_OWNED_COUNT=$((MANIFEST_OWNED_COUNT + 1))
	fi
}

record_native_previous_checkpoint() {
	UPGRADE_OLD_VERSION=$MANIFEST_CURRENT_VERSION
	UPGRADE_OLD_BINARY_SHA256=$MANIFEST_CURRENT_BINARY_SHA256
	MANIFEST_PREVIOUS_VERSION=$UPGRADE_OLD_VERSION
	MANIFEST_PREVIOUS_BINARY_PATH=$MANIFEST_PREVIOUS_BINARY_PATH_FIXED
	MANIFEST_PREVIOUS_BINARY_SHA256=$UPGRADE_OLD_BINARY_SHA256
	MANIFEST_PREVIOUS_IMAGE=""
	manifest_add_previous_native_paths || return 1
	manifest_write "$INSTALL_RECORD"
}

record_upgrade_target() {
	old_version=$MANIFEST_CURRENT_VERSION
	old_binary_path=$MANIFEST_CURRENT_BINARY_PATH
	old_binary_sha256=$MANIFEST_CURRENT_BINARY_SHA256
	old_image=$MANIFEST_CURRENT_IMAGE

	MANIFEST_PREVIOUS_VERSION=$old_version
	MANIFEST_PREVIOUS_BINARY_PATH=$old_binary_path
	MANIFEST_PREVIOUS_BINARY_SHA256=$old_binary_sha256
	MANIFEST_PREVIOUS_IMAGE=$old_image
	MANIFEST_CURRENT_VERSION=$ONE_NODE_VERSION
	MANIFEST_DESIRED_CONFIG_REVISION=$ONE_NODE_EXPECTED_CONFIG_REVISION
	MANIFEST_DESIRED_BINDINGS_REVISION=$ONE_NODE_EXPECTED_BINDINGS_REVISION
	if [ "$MANIFEST_MODE" = native ]; then
		MANIFEST_CURRENT_BINARY_PATH=$MANIFEST_BINARY_PATH
		MANIFEST_CURRENT_BINARY_SHA256=$ONE_NODE_BINARY_SHA256
		MANIFEST_CURRENT_IMAGE=""
		MANIFEST_PREVIOUS_BINARY_PATH=$MANIFEST_PREVIOUS_BINARY_PATH_FIXED
		manifest_add_previous_native_paths || return 1
	else
		MANIFEST_CURRENT_BINARY_PATH=""
		MANIFEST_CURRENT_BINARY_SHA256=""
		MANIFEST_CURRENT_IMAGE=$ONE_NODE_DOCKER_IMAGE
		MANIFEST_PREVIOUS_BINARY_PATH=""
		MANIFEST_PREVIOUS_BINARY_SHA256=""
	fi
	manifest_write "$INSTALL_RECORD"
}

record_rollback_target() {
	rollback_version=$MANIFEST_PREVIOUS_VERSION
	rollback_binary_path=$MANIFEST_PREVIOUS_BINARY_PATH
	rollback_binary_sha256=$MANIFEST_PREVIOUS_BINARY_SHA256
	rollback_image=$MANIFEST_PREVIOUS_IMAGE
	[ -n "$rollback_version" ] || return 1

	MANIFEST_PREVIOUS_VERSION=$MANIFEST_CURRENT_VERSION
	MANIFEST_PREVIOUS_BINARY_PATH=$MANIFEST_CURRENT_BINARY_PATH
	MANIFEST_PREVIOUS_BINARY_SHA256=$MANIFEST_CURRENT_BINARY_SHA256
	MANIFEST_PREVIOUS_IMAGE=$MANIFEST_CURRENT_IMAGE
	MANIFEST_CURRENT_VERSION=$rollback_version
	MANIFEST_CURRENT_BINARY_PATH=$rollback_binary_path
	MANIFEST_CURRENT_BINARY_SHA256=$rollback_binary_sha256
	MANIFEST_CURRENT_IMAGE=$rollback_image
	if [ "$MANIFEST_MODE" = native ]; then
		MANIFEST_CURRENT_BINARY_PATH=$MANIFEST_BINARY_PATH
		MANIFEST_PREVIOUS_BINARY_PATH=$MANIFEST_PREVIOUS_BINARY_PATH_FIXED
	fi
	manifest_write "$INSTALL_RECORD"
}
